### PR TITLE
fix search override on focus/mouseenter

### PR DESCRIPTION
**Pull request by mohsinulhaq**
Fixes https://github.com/react-pdf-viewer/react-pdf-viewer/issues/1193

### CODE REVIEW

**Comment by mohsinulhaq** [comment]
@phuoc-ng could you please look into this?

**Comment by mohsinulhaq** [comment]
@phuoc-ng ?

**Comment by phuoc-ng** [comment]
Thanks you!

**Comment by mohsinulhaq** [comment]
What's the reason that you don't merge our PRs directly?

**Comment by phuoc-ng** [comment]
I am sorry, @mohsinulhaq! The product is commercial, so it doesn't accept any PRs from the beginning.
Thanks for reporting the issue and the suggestion.

**Pull request closed without merging**
